development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tax_app
  username: postgres
  password: postgres123
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tax_app
  username: postgres
  password: postgres123

